services:
  adminer:
    image: 'adminer:latest'
    ports:
      - 9083:8080
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=accounts'
      - 'POSTGRES_PASSWORD=account'
      - 'POSTGRES_USER=account'
    volumes:
      - ./accounts-data:/var/lib/postgresql/data
    ports:
      - '5432'
